export enum DocumentStatus {
    // Fluxo Básico
    PENDING = 'PENDING',
    ANALYZING = 'ANALYZING',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',

    // Fluxo de Apostilamento
    WAITING_APOSTILLE = 'WAITING_APOSTILLE',
    WAITING_APOSTILLE_QUOTE = 'WAITING_APOSTILLE_QUOTE',
    ANALYZING_APOSTILLE_PAYMENT = 'ANALYZING_APOSTILLE_PAYMENT',
    EXECUTING_APOSTILLE = 'EXECUTING_APOSTILLE',
    ANALYZING_APOSTILLE = 'ANALYZING_APOSTILLE',

    // Fluxo de Tradução
    WAITING_TRANSLATION = 'WAITING_TRANSLATION',
    WAITING_TRANSLATION_QUOTE = 'WAITING_TRANSLATION_QUOTE',
    WAITING_QUOTE_APPROVAL = 'WAITING_QUOTE_APPROVAL',
    ANALYZING_TRANSLATION_PAYMENT = 'ANALYZING_TRANSLATION_PAYMENT',
    EXECUTING_TRANSLATION = 'EXECUTING_TRANSLATION',
    ANALYZING_TRANSLATION = 'ANALYZING_TRANSLATION',
}
